version: '3.8'

services:
  lamp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital_lamp
    ports:
      - "80:80"
    volumes:
      - ../hospital_app:/var/www/html
    environment:
      - DB_HOST=db-vm
      - DB_NAME=hospital_db
      - DB_USER=hospital_user
      - DB_PASS=HospitalPass123!
    restart: always
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

